### ISSUE TITLE
Buildpack require to install this script on Heroku

### ISSUE THREAD

**Issue by ghost** [KANG-NEWBIE/y2mapi#1]
hi 
what are the Buildpack require to install this script on Heroku .

**Comment by erickythierry** [comment]
> hi
> what are the Buildpack require to install this script on Heroku .

only python

**Comment by therealvkr** [comment]
can you please share - requirements.txt and Procfile File ..
I think due to these file this error message is being seen

**Comment by erickythierry** [comment]
> can you please share - requirements.txt and Procfile File ..
> I think due to these file this error message is being seen

this project is broken. I tried to run on my machine, but it didn't work

**Comment by therealvkr** [comment]
Your project is start working  but still i get Application Error Please Share Your Procfile  and Requirement.txt

**Comment by erickythierry** [comment]
> Your project is start working but still i get Application Error Please Share Your Procfile and Requirement.txt

this project is not a downloader. is just a customer for "https://nuubi.herokuapp.com".
see the `y2mate-dl.py` file. it's just accesses that site and receives the resulting file. if the site above stops working, this project will also stop. the back end was not posted for us to know how to make the downloads without relying on an external api
